const fs = require("fs"); 
require("dotenv").config();

module.exports = {
    prefix: process.env.PREFIX || "*",
    ownerName: process.env.OWNER_NAME || "Warano",
    ownerNumber: process.env.OWNER_NUMBER || "237621092130",
    mode: process.env.MODE || "private",
    region: process.env.REGION || "Waratack",
    botName: process.env.BOT_NAME || "Waratack v1",
    exifPack: process.env.EXIF_PACK || "Warano Loves",
    exifAuthor: process.env.EXIF_AUTHOR || "Toxxic Warano",
    timeZone: process.env.TIME_ZONE || "Africa/Lagos",
    presenceStatus: process.env.PRESENCE_STATUS || "unavailable",
    autoRead: process.env.AUTO_READ === "false",
    autoViewStatus: process.env.AUTO_VIEW_STATUS === "true",
    autoReact: process.env.AUTO_REACT === "true",
    sessionId: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZ01lZnpVdVZGamh4ZFRZckZGK3pSVk00eklvK0FRSGlXVFZqY01SbmQwcz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUHNBaHpkeFYrZldNT3ZydEZCY0Q5MnhweHgvL2RxM0owSDArYUFud2xVdz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJpTDZpV0RwbXAydHpPVFdXSTRmWGxtWFpyWlp3d0FHVC9kYkNHUjlWclhZPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJXeE1lcWkzUnVBTE1HalBPdDErWndrOTU5bVlwZTA2eFMrclFidjYydVRzPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IndIM1BPbnV0NzFNZ0t0YUlCS0lNMmZ2UUt1WmFoc3czdm50L0ZNVjRXMFk9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ikg5a2c1U2pWeXZWTkZRSHRQNkZQMXp4bmRiTjE0dGF4NTBVRzJMWmZ2Z0E9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiS0M0MFhBenZWMTJPc3JUd3pHZ0FKbFo2bVJMbnhyY0NHcUxCWm5VNXVHST0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNE5IbVY3dmIwQWpnNGQrK3d5dlFaTVk1N2NDUWdnbVNtVTVLRHZNaWR3cz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjIyazNlNFlKQkxraCtzVFhHRXZxcklPVkNISXN0M0hDNGJodDlaU3R4dndzNms5TE54OGZib3dVYnF5SzRqajRZQUNITUVNOGp5SUhZNUlFMlNSa2h3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MzYsImFkdlNlY3JldEtleSI6InJvZVFLTjRnbkFqV2YrVjRkRlM5anBONkRsMythSkp5YUtseFFHam9qeWc9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbXSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJyZWdpc3RlcmVkIjp0cnVlLCJwYWlyaW5nQ29kZSI6IkpCVFo5U0g1IiwibWUiOnsiaWQiOiIyMzc2MjEwOTIxMzA6OTdAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoiV2FyYW5vIiwibGlkIjoiODkyNzEyOTc5Mzc2MDc6OTdAbGlkIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNMalM3SXdERUtPVHFyMEdHQklnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJ6TFRFZ0kwbDNuNjMyMTFsY0NYc0cySTlGZWRwQit2NmtZU2tiQm43SVN3PSIsImFjY291bnRTaWduYXR1cmUiOiIwMXZXYkNheWxxakxySHB6SFNGMWFMYTNIUGd0N0ptUndFRmIra0hpZWc3ZGQxTE4wZ21qTXM4akRRQllQM3NHY2lGaXZVZWR2K1JWY2dYS2htNXhBdz09IiwiZGV2aWNlU2lnbmF0dXJlIjoicVlIRy83d3NaemU3bVJ5SGNKTlUwRTk3d2VSbEQ3NkxMSTlEYWtsOXIrWUJqSEJVb2VCcnF3QnY1QW9Lang5dm9qYmM2TXk1T3g3VTdhUk1UTk16akE9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyMzc2MjEwOTIxMzA6OTdAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCY3kweElDTkpkNSt0OXRkWlhBbDdCdGlQUlhuYVFmcitwR0VwR3daK3lFcyJ9fV0sInBsYXRmb3JtIjoic21iYSIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0EwSUNBPT0ifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzM5MjI5NjE2LCJsYXN0UHJvcEhhc2giOiIzZ1BVSmsiLCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUtPNyJ9",
    autoRejectEnabled: process.env.AUTO_REJECT_ENABLED || "false",
};

let file = require.resolve(__filename); 
fs.watchFile(file, () => {
    fs.unwatchFile(file); 
    console.log(`Update '${__filename}'`); 
    delete require.cache[file];
    require(file); 
});
