const fs = require("fs"); 
require("dotenv").config();

module.exports = {
    prefix: process.env.PREFIX || "*",
    ownerName: process.env.OWNER_NAME || "Warano",
    ownerNumber: process.env.OWNER_NUMBER || "237621092130",
    mode: process.env.MODE || "public",
    region: process.env.REGION || "Waratack",
    botName: process.env.BOT_NAME || "Waratack v1",
    exifPack: process.env.EXIF_PACK || "Warano Loves",
    exifAuthor: process.env.EXIF_AUTHOR || "Toxxic Warano",
    timeZone: process.env.TIME_ZONE || "Africa/Lagos",
    presenceStatus: process.env.PRESENCE_STATUS || "unavailable",
    autoRead: process.env.AUTO_READ === "false",
    autoViewStatus: process.env.AUTO_VIEW_STATUS === "true",
    autoReact: process.env.AUTO_REACT === "true",
    sessionId: process.env.SESSION_ID ||"eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoieUY0ZHhtZ3dOcFQ1OWtmQVpYeG5tdGVGU0VvbW0vR0N2SEpiVm96b3dVVT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQVZ3UWJFYkY2Wm1PRUk2b1pJYTR1a2ZyQUVXVFBYUGFrcnlUOFFFZ05ucz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJjQVI4Ym9rTVVTTHhqdzFPdVpnWStIL0lpSklCL05PU1VTT0k0a0xjaFdjPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJkU0c4T0N6eFpKc1Jqb2pZd0NOYlBnKzRYamd1TEF3NEl6eHplb2RYSHdrPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImlNS25sOXU3ODFSbHB5aExWcG1OcXpKbmtnZkJqNVI5Z0lkay9jT3IvRm89In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InQwTEZUcHpIWXNMMTlJd0FHZ0NacW10Qml3UzF0eWpGRjJxMHc5TWFNWGc9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVU51ejd2VGJKTmw1UUM3RTZFWGcwblAyMllJOUU0MktIaVFYR20yT3EyRT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUXlkSENEbC9hOWNwNDJjUUlHUkxnaWxEUndyaUVOUXZDcDM1RHhwaFBtVT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjN5TmVKQjA5Z3MrVnZkenhKSVRNNWFROEFVZ2JxaWhINDJMWnBWcmFrUmZ6TDZicWhGYUdoZ1NXVjlQakxVTGF4blU2WVhqUmlWb0VLVzNWbzErdUN3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTcwLCJhZHZTZWNyZXRLZXkiOiJRaGVDcjJMRytjS1N5VkVaMEtoeDFqayttVUZsS3RocDYvTDFsdXJaT3A4PSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6dHJ1ZSwicGFpcmluZ0NvZGUiOiJaTERWRE0yQyIsIm1lIjp7ImlkIjoiMjM3NjIxMDkyMTMwOjFAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoiV2FyYW5vIiwibGlkIjoiODkyNzEyOTc5Mzc2MDc6MUBsaWQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0xqUzdJd0RFTTJSckwwR0dCUWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6InpMVEVnSTBsM242MzIxMWxjQ1hzRzJJOUZlZHBCK3Y2a1lTa2JCbjdJU3c9IiwiYWNjb3VudFNpZ25hdHVyZSI6IlMxN3NBZFJPOU9teVhSck5WS2pjUko5a0NmdlBYdVZEUTdacUsvZE9UblluSE45Z2ZVendQMitMVUFXOTFOUENRYzJMQlRhVmo0REhJbDBOOG5VNkJ3PT0iLCJkZXZpY2VTaWduYXR1cmUiOiIxMmUvdmY1WUdWcVgzQ0J0SjdCNy8zcis5MG1NNTBGYlZLMUE0djZZYml3Q2hNYTlUM29LVTlRMUZHOTVvZXZXbEFVV3J5d3dHcHh4YzA3M3gyUHBEdz09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjIzNzYyMTA5MjEzMDoxQHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQmN5MHhJQ05KZDUrdDl0ZFpYQWw3QnRpUFJYbmFRZnIrcEdFcEd3Wit5RXMifX1dLCJwbGF0Zm9ybSI6InNtYmEiLCJyb3V0aW5nSW5mbyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkNBMElDQT09In0sImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTczOTI2MjE3MSwibGFzdFByb3BIYXNoIjoiM2dQVUprIn0=",
    autoRejectEnabled: process.env.AUTO_REJECT_ENABLED || "false",
};

let file = require.resolve(__filename); 
fs.watchFile(file, () => {
    fs.unwatchFile(file); 
    console.log(`Update '${__filename}'`); 
    delete require.cache[file];
    require(file); 
});
